name: Ticker-Screener
on:
  schedule:
    - cron: '0 * * * *' # Läuft jede Stunde
  workflow_dispatch:     # Erlaubt manuelles Starten per Klick

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Von v3 auf v4 geändert

      - name: Set up Python
        uses: actions/setup-python@v5  # Von v4 auf v5 geändert
        with:
          python-version: '3.10'